# Generated by Django 4.2.4 on 2023-08-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyborg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatabela',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='novatabela',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
